In [1]:
import os
os.getcwd()

'Z:\\jupyter notebook files\\EE Capstone\\play_ckd'

In [2]:
import torch
import importlib
import torch.nn as nn
import numpy as np

from tabulate import tabulate

from get_args_parser import get_args_parser
#from engine_test import evaluate_cmc, evaluate_p2p_eer
from dataset import get_identification_dataloaders, get_verification_dataloaders
from main_test import test_p2p_verification, test_f2f_verification, test_p2f_verification
from main_test import test_p2p_identification, test_f2f_identification, test_p2f_identification

from models.load_trained_models import load_trained_ckd
from misc.utils_torch import set_seed
from misc.utils_python import get_paths, import_yaml_config, generate_pairs

In [3]:
torch.cuda.is_available()

True

In [4]:
parser = get_args_parser()
args = parser.parse_args('')
args = import_yaml_config(args)
args.device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

if args.seed != None:
  set_seed(0)
args = get_paths(args)

print(tabulate(list(vars(args).items()), headers=['arguments', 'values']))

arguments       values
--------------  --------------------------------------------------------------------------------------------------------------------------
config_name     ckd_config01
gpu_num         1
num_workers     8
tb_log          False
seed
data_root_path  Z:\image_datasets
save_root_path  ./saved_models
model_name      CKD
backbone_name   resnet18
train_config    {'num_epochs': 90, 'batch_size': 512, 'lr': 0.1, 'milestones': [30, 60, 80], 'momentum': 0.9, 'weight_decay_rate': 0.0005}
model_config    {'tau': 2.5}
device          cuda
save_dir_path   ./saved_models/ckd_config01
log_dir_path    ./logs/result_log/ckd_config01
tb_dir_path     ./logs/tb_log/ckd_config01/2022-08-06-20-23-42


In [5]:
model_modules = importlib.import_module('models.{}'.format(args.model_name))

args.num_classes = 1054

model = model_modules.make_model(args)
model = model.to(args.device)
load_trained_ckd(model, f"{args.save_dir_path}/model_best.pth" )

args.num_workers = 4

In [6]:
test_p2p_identification(args, model)

The periocular-to-periocular CMC of ethnic start



52it [00:09,  5.76it/s]
756it [01:30,  8.39it/s]


0.94105 



756it [01:30,  8.38it/s]
52it [00:06,  7.63it/s]


0.97082 


The periocular-to-periocular CMC of ethnic :
[0.955935 0.967755 0.972735 0.976355 0.978535]

The periocular-to-periocular CMC of pubfig start



289it [00:35,  8.25it/s]
240it [00:30,  7.99it/s]


1.0 



289it [00:34,  8.35it/s]
192it [00:24,  7.88it/s]


0.98843 



289it [00:34,  8.38it/s]
191it [00:23,  8.02it/s]


0.98722 



240it [00:28,  8.33it/s]
289it [00:34,  8.27it/s]


0.9769 



240it [00:28,  8.31it/s]
192it [00:23,  8.24it/s]


0.98843 



240it [00:28,  8.32it/s]
191it [00:23,  8.21it/s]


0.98689 



192it [00:23,  8.28it/s]
289it [00:34,  8.33it/s]


0.93949 



192it [00:23,  8.31it/s]
240it [00:29,  8.26it/s]


0.95964 



192it [00:23,  8.28it/s]
191it [00:23,  8.24it/s]


0.98082 



191it [00:23,  8.30it/s]
289it [00:34,  8.32it/s]


0.94209 



191it [00:23,  8.29it/s]
240it [00:29,  8.27it/s]


0.9599 



191it [00:22,  8.31it/s]
192it [00:23,  8.21it/s]


0.98403 


The periocular-to-periocular CMC of pubfig :
[0.97448667 0.98236167 0.9854475  0.98739417 0.98869917]

The periocular-to-periocular CMC of facescrub start



971it [01:54,  8.45it/s]
673it [01:22,  8.13it/s]


0.98406 



971it [01:54,  8.46it/s]
853it [01:46,  8.04it/s]


0.97409 



673it [01:19,  8.45it/s]
971it [01:56,  8.36it/s]


0.96449 



673it [01:19,  8.44it/s]
853it [01:42,  8.35it/s]


0.97157 



853it [01:40,  8.45it/s]
971it [01:56,  8.33it/s]


0.96614 



853it [01:41,  8.44it/s]
673it [01:20,  8.31it/s]


0.98369 


The periocular-to-periocular CMC of facescrub :
[0.97400667 0.98002    0.982215   0.98361833 0.98452667]

The periocular-to-periocular CMC of imdb_wiki start



1258it [02:28,  8.46it/s]
552it [01:08,  8.04it/s]


0.86448 



1258it [02:29,  8.44it/s]
477it [00:59,  7.98it/s]


0.89752 



1258it [02:28,  8.47it/s]
509it [01:03,  8.01it/s]


0.90069 



552it [01:05,  8.42it/s]
1258it [02:29,  8.40it/s]


0.77197 



552it [01:05,  8.42it/s]
477it [00:57,  8.35it/s]


0.87497 



552it [01:05,  8.41it/s]
509it [01:00,  8.35it/s]


0.87132 



477it [00:56,  8.42it/s]
1258it [02:29,  8.42it/s]


0.74829 



477it [00:56,  8.40it/s]
552it [01:05,  8.37it/s]


0.81793 



477it [00:56,  8.39it/s]
509it [01:00,  8.37it/s]


0.8664 



509it [01:00,  8.42it/s]
1258it [02:30,  8.37it/s]


0.7628 



509it [01:00,  8.38it/s]
552it [01:06,  8.33it/s]


0.81918 



509it [01:00,  8.40it/s]
477it [00:57,  8.35it/s]


0.87287 


The periocular-to-periocular CMC of imdb_wiki :
[0.839035   0.87644667 0.8919175  0.9012975  0.9079975 ]

The periocular-to-periocular CMC of ar start



22it [00:03,  6.22it/s]
88it [00:11,  7.63it/s]


0.83464 



22it [00:03,  6.73it/s]
44it [00:06,  7.24it/s]


0.99 



22it [00:03,  7.06it/s]
110it [00:13,  8.01it/s]


0.972 



22it [00:03,  6.60it/s]
19it [00:05,  3.71it/s]


0.99833 



88it [00:10,  8.09it/s]
22it [00:03,  6.89it/s]


0.98143 



88it [00:10,  8.12it/s]
44it [00:05,  7.72it/s]


1.0 



88it [00:10,  8.19it/s]
110it [00:13,  8.20it/s]


0.99743 



88it [00:10,  8.02it/s]
19it [00:04,  3.92it/s]


0.99333 



44it [00:05,  7.67it/s]
22it [00:03,  6.74it/s]


0.99 



44it [00:05,  7.63it/s]
88it [00:10,  8.16it/s]


0.93357 



44it [00:05,  7.64it/s]
110it [00:13,  8.20it/s]


0.99857 



44it [00:05,  7.60it/s]
19it [00:04,  3.92it/s]


0.99833 



110it [00:13,  8.15it/s]
22it [00:03,  6.77it/s]


0.99286 



110it [00:13,  8.20it/s]
88it [00:10,  8.09it/s]


0.91821 



110it [00:13,  8.19it/s]
44it [00:05,  7.59it/s]


0.99857 



110it [00:13,  8.18it/s]
19it [00:04,  3.85it/s]


0.99833 



19it [00:04,  4.02it/s]
22it [00:03,  6.79it/s]


0.95 



19it [00:04,  3.95it/s]
88it [00:10,  8.04it/s]


0.80107 



19it [00:04,  3.85it/s]
44it [00:05,  7.62it/s]


0.93857 



19it [00:04,  3.93it/s]
110it [00:13,  8.22it/s]


0.92371 


The periocular-to-periocular CMC of ar :
[0.9604475 0.9696045 0.9753595 0.978839  0.9814045]

The periocular-to-periocular CMC of ytf start



4696it [09:13,  8.48it/s]
1157it [02:40,  7.22it/s]


0.73329 



1157it [02:16,  8.47it/s]
4696it [09:40,  8.08it/s]


0.5365 


The periocular-to-periocular CMC of ytf :
[0.634895 0.66516  0.68367  0.69608  0.706185]

The periocular-to-periocular CMC dictionary : 
{'ethnic': array([0.955935, 0.967755, 0.972735, 0.976355, 0.978535]), 'pubfig': array([0.97448667, 0.98236167, 0.9854475 , 0.98739417, 0.98869917]), 'facescrub': array([0.97400667, 0.98002   , 0.982215  , 0.98361833, 0.98452667]), 'imdb_wiki': array([0.839035  , 0.87644667, 0.8919175 , 0.9012975 , 0.9079975 ]), 'ar': array([0.9604475, 0.9696045, 0.9753595, 0.978839 , 0.9814045]), 'ytf': array([0.634895, 0.66516 , 0.68367 , 0.69608 , 0.706185])}


In [9]:
test_f2f_identification(args, model)

The face-to-face CMC of ethnic start



52it [00:06,  7.48it/s]
756it [01:30,  8.36it/s]


0.95664 



756it [01:29,  8.46it/s]
52it [00:06,  7.65it/s]


0.97386 


The face-to-face CMC of ethnic :
[0.96525  0.97503  0.97886  0.98102  0.982765]

The face-to-face CMC of pubfig start



289it [00:34,  8.28it/s]
240it [00:29,  8.11it/s]


1.0 



289it [00:34,  8.36it/s]
192it [00:24,  7.93it/s]


0.99169 



289it [00:34,  8.36it/s]
191it [00:23,  7.98it/s]


0.99246 



240it [00:28,  8.31it/s]
289it [00:34,  8.27it/s]


0.98352 



240it [00:28,  8.28it/s]
192it [00:23,  8.19it/s]


0.99218 



240it [00:28,  8.32it/s]
191it [00:23,  8.17it/s]


0.99115 



192it [00:23,  8.31it/s]
289it [00:34,  8.32it/s]


0.95358 



192it [00:23,  8.26it/s]
240it [00:29,  8.23it/s]


0.96836 



192it [00:23,  8.30it/s]
191it [00:23,  8.22it/s]


0.98722 



191it [00:23,  8.29it/s]
289it [00:34,  8.29it/s]


0.95705 



191it [00:22,  8.34it/s]
240it [00:29,  8.25it/s]


0.97135 



191it [00:23,  8.30it/s]
192it [00:23,  8.24it/s]


0.99022 


The face-to-face CMC of pubfig :
[0.981565   0.98756917 0.99024583 0.99181083 0.99255833]

The face-to-face CMC of facescrub start



971it [01:55,  8.43it/s]
673it [01:22,  8.13it/s]


0.98736 



971it [01:55,  8.44it/s]
853it [01:44,  8.14it/s]


0.97926 



673it [01:19,  8.42it/s]
971it [01:56,  8.31it/s]


0.97142 



673it [01:20,  8.37it/s]
853it [01:45,  8.11it/s]


0.97743 



853it [01:42,  8.36it/s]
971it [01:58,  8.22it/s]


0.97232 



853it [01:41,  8.38it/s]
673it [01:21,  8.25it/s]


0.98722 


The face-to-face CMC of facescrub :
[0.97916833 0.984295   0.98591333 0.98688    0.98758333]

The face-to-face CMC of imdb_wiki start



1258it [02:29,  8.41it/s]
552it [01:09,  7.95it/s]


0.8856 



1258it [02:29,  8.43it/s]
477it [00:59,  7.99it/s]


0.91719 



1258it [02:30,  8.36it/s]
509it [01:03,  8.03it/s]


0.9179 



552it [01:05,  8.42it/s]
1258it [02:29,  8.39it/s]


0.80505 



552it [01:05,  8.40it/s]
477it [00:57,  8.33it/s]


0.89359 



552it [01:05,  8.42it/s]
509it [01:01,  8.34it/s]


0.89523 



477it [00:56,  8.41it/s]
1258it [02:29,  8.41it/s]


0.78256 



477it [00:56,  8.39it/s]
552it [01:05,  8.37it/s]


0.84426 



477it [00:56,  8.40it/s]
509it [01:00,  8.35it/s]


0.8889 



509it [01:00,  8.41it/s]
1258it [02:29,  8.39it/s]


0.79618 



509it [01:00,  8.40it/s]
552it [01:06,  8.34it/s]


0.85281 



509it [01:00,  8.41it/s]
477it [00:57,  8.33it/s]


0.89601 


The face-to-face CMC of imdb_wiki :
[0.86460667 0.8983575  0.91166083 0.9192775  0.92510417]

The face-to-face CMC of ar start



22it [00:03,  6.00it/s]
88it [00:11,  7.62it/s]


0.63929 



22it [00:03,  6.73it/s]
44it [00:06,  7.10it/s]


0.98643 



22it [00:03,  7.02it/s]
110it [00:13,  7.95it/s]


0.976 



22it [00:03,  6.82it/s]
19it [00:05,  3.67it/s]


0.99667 



88it [00:10,  8.05it/s]
22it [00:03,  7.00it/s]


0.98286 



88it [00:11,  7.86it/s]
44it [00:05,  7.64it/s]


1.0 



88it [00:10,  8.12it/s]
110it [00:13,  8.22it/s]


0.99914 



88it [00:10,  8.06it/s]
19it [00:04,  3.89it/s]


0.995 



44it [00:05,  7.56it/s]
22it [00:03,  6.82it/s]


0.98857 



44it [00:05,  7.70it/s]
88it [00:10,  8.08it/s]


0.76107 



44it [00:05,  7.60it/s]
110it [00:13,  8.17it/s]


1.0 



44it [00:05,  7.73it/s]
19it [00:04,  3.91it/s]


0.99833 



110it [00:13,  8.13it/s]
22it [00:03,  6.71it/s]


0.98714 



110it [00:13,  8.19it/s]
88it [00:11,  7.99it/s]


0.73179 



110it [00:13,  8.16it/s]
44it [00:05,  7.55it/s]


0.99857 



110it [00:13,  8.14it/s]
19it [00:04,  3.85it/s]


1.0 



19it [00:04,  3.90it/s]
22it [00:03,  6.87it/s]


0.95429 



19it [00:04,  3.98it/s]
88it [00:10,  8.16it/s]


0.61857 



19it [00:04,  3.87it/s]
44it [00:05,  7.58it/s]


0.94857 



19it [00:04,  3.93it/s]
110it [00:13,  8.14it/s]


0.93829 


The face-to-face CMC of ar :
[0.925029 0.937879 0.944534 0.949669 0.95327 ]

The face-to-face CMC of ytf start



4696it [09:14,  8.46it/s]
1157it [02:40,  7.23it/s]


0.80746 



1157it [02:17,  8.44it/s]
4696it [09:36,  8.14it/s]


0.61797 


The face-to-face CMC of ytf :
[0.712715 0.73846  0.755395 0.767875 0.77666 ]

The face-to-face CMC dictionary : 
{'ethnic': array([0.96525 , 0.97503 , 0.97886 , 0.98102 , 0.982765]), 'pubfig': array([0.981565  , 0.98756917, 0.99024583, 0.99181083, 0.99255833]), 'facescrub': array([0.97916833, 0.984295  , 0.98591333, 0.98688   , 0.98758333]), 'imdb_wiki': array([0.86460667, 0.8983575 , 0.91166083, 0.9192775 , 0.92510417]), 'ar': array([0.925029, 0.937879, 0.944534, 0.949669, 0.95327 ]), 'ytf': array([0.712715, 0.73846 , 0.755395, 0.767875, 0.77666 ])}
time elapsed : 1h 117m 0.23s


In [6]:
test_p2p_verification(args, model)

The periocular-to-periocular EER of ethnic start



42it [00:11,  3.77it/s]



The periocular-to-periocular EER of ethnic : 0.06119

The periocular-to-periocular EER of pubfig start



25it [00:03,  6.39it/s]



The periocular-to-periocular EER of pubfig : 0.05564

The periocular-to-periocular EER of facescrub start



67it [00:08,  7.67it/s]



The periocular-to-periocular EER of facescrub : 0.02835

The periocular-to-periocular EER of imdb_wiki start



267it [00:32,  8.28it/s]



The periocular-to-periocular EER of imdb_wiki : 0.06588

The periocular-to-periocular EER of ar start



13it [00:04,  2.82it/s]



The periocular-to-periocular EER of ar : 0.07128

The periocular-to-periocular EER of ytf start



29it [00:14,  1.94it/s]



The periocular-to-periocular EER of ytf : 0.15041

The periocular-to-periocular EER dictionary : 
{'ethnic': 0.06119, 'pubfig': 0.05564, 'facescrub': 0.02835, 'imdb_wiki': 0.06588, 'ar': 0.07128, 'ytf': 0.15041}
time elapsed : 0h 2m 49.35s


In [7]:
test_f2f_verification(args, model)

The face-to-face EER of ethnic start



42it [00:05,  7.67it/s]



The face-to-face EER of ethnic : 0.05321

The face-to-face EER of pubfig start



25it [00:03,  7.07it/s]



The face-to-face EER of pubfig : 0.04654

The face-to-face EER of facescrub start



67it [00:08,  7.98it/s]



The face-to-face EER of facescrub : 0.02428

The face-to-face EER of imdb_wiki start



267it [00:31,  8.34it/s]



The face-to-face EER of imdb_wiki : 0.05748

The face-to-face EER of ar start



13it [00:04,  3.01it/s]



The face-to-face EER of ar : 0.07672

The face-to-face EER of ytf start



29it [00:03,  7.37it/s]



The face-to-face EER of ytf : 0.13719

The face-to-face EER dictionary : 
{'ethnic': 0.05321, 'pubfig': 0.04654, 'facescrub': 0.02428, 'imdb_wiki': 0.05748, 'ar': 0.07672, 'ytf': 0.13719}
time elapsed : 0h 2m 10.66s
