In [1]:
import os
os.getcwd()

'Z:\\jupyter notebook files\\EE Capstone\\play_ckd'

In [2]:
import torch
import importlib
import torch.nn as nn
import numpy as np

from tabulate import tabulate

from get_args_parser import get_args_parser

from dataset import get_identification_dataloaders, get_verification_dataloaders

from main_test import test_f2p_identification_cos_sim, test_f2p_verification_cos_sim
from main_test import test_f2p_identification_kl_div, test_f2p_verification_kl_div

from models.load_trained_models import load_trained_ckd
from misc.utils_torch import set_seed
from misc.utils_python import get_paths, import_yaml_config, generate_pairs

In [3]:
torch.cuda.is_available()

True

In [4]:
parser = get_args_parser()
args = parser.parse_args('')
args = import_yaml_config(args)
args.device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

if args.seed != None:
    set_seed(0)
args = get_paths(args)

print(tabulate(list(vars(args).items()), headers=['arguments', 'values']))

arguments       values
--------------  --------------------------------------------------------------------------------------------------------------------------
config_name     ckd_config01
gpu_num         1
num_workers     8
tb_log          False
seed
data_root_path  Z:\image_datasets
save_root_path  ./saved_models
model_name      CKD
backbone_name   resnet18
train_config    {'num_epochs': 90, 'batch_size': 512, 'lr': 0.1, 'milestones': [30, 60, 80], 'momentum': 0.9, 'weight_decay_rate': 0.0005}
model_config    {'tau': 2.5}
device          cuda
save_dir_path   ./saved_models/ckd_config01
log_dir_path    ./logs/result_log/ckd_config01
tb_dir_path     ./logs/tb_log/ckd_config01/2022-08-29-10-57-12


In [5]:
model_modules = importlib.import_module('models.{}'.format(args.model_name))

args.num_classes = 1054

model = model_modules.make_model(args)
model = model.to(args.device)
load_trained_ckd(model, f"{args.save_dir_path}/model_best.pth" )

args.num_workers = 4

In [6]:
test_f2p_identification_cos_sim(args, model)

The face-to-periocular CMC of ethnic start



52it [00:09,  5.38it/s]
756it [01:31,  8.28it/s]


0.93352 



756it [01:29,  8.44it/s]
52it [00:06,  7.66it/s]


0.97447 


The face-to-periocular CMC of ethnic :
[0.953995 0.968065 0.97396  0.976825 0.97868 ]
It took 3m 57s

The face-to-periocular CMC of pubfig start



289it [00:35,  8.25it/s]
240it [00:29,  8.08it/s]


1.0 



289it [00:34,  8.34it/s]
192it [00:24,  7.89it/s]


0.98469 



289it [00:34,  8.33it/s]
191it [00:23,  8.00it/s]


0.98443 



240it [00:28,  8.29it/s]
289it [00:34,  8.28it/s]


0.97592 



240it [00:28,  8.29it/s]
192it [00:23,  8.18it/s]


0.98403 



240it [00:28,  8.29it/s]
191it [00:23,  8.19it/s]


0.98361 



192it [00:23,  8.26it/s]
289it [00:34,  8.30it/s]


0.93179 



192it [00:23,  8.25it/s]
240it [00:29,  8.26it/s]


0.95195 



192it [00:23,  8.22it/s]
191it [00:23,  8.19it/s]


0.97836 



191it [00:23,  8.21it/s]
289it [00:34,  8.32it/s]


0.93634 



191it [00:23,  8.24it/s]
240it [00:28,  8.28it/s]


0.95547 



191it [00:23,  8.27it/s]
192it [00:23,  8.24it/s]


0.97931 


The face-to-periocular CMC of pubfig :
[0.97049167 0.97919667 0.9827375  0.98477083 0.98623083]
It took 14m 58s

The face-to-periocular CMC of facescrub start



971it [01:55,  8.39it/s]
673it [01:23,  8.07it/s]


0.98155 



971it [01:56,  8.34it/s]
853it [01:45,  8.07it/s]


0.9697 



673it [01:20,  8.34it/s]
971it [01:59,  8.14it/s]


0.9607 



673it [01:20,  8.39it/s]
853it [01:44,  8.18it/s]


0.96728 



853it [01:41,  8.40it/s]
971it [01:57,  8.27it/s]


0.96266 



853it [01:41,  8.40it/s]
673it [01:21,  8.25it/s]


0.9816 


The face-to-periocular CMC of facescrub :
[0.97058167 0.97709667 0.979755   0.98130833 0.982425  ]
It took 22m 20s

The face-to-periocular CMC of imdb_wiki start



1258it [02:29,  8.39it/s]
552it [01:09,  7.98it/s]


0.84834 



1258it [02:30,  8.38it/s]
477it [01:00,  7.92it/s]


0.88644 



1258it [02:29,  8.43it/s]
509it [01:03,  7.99it/s]


0.88853 



552it [01:05,  8.37it/s]
1258it [02:30,  8.33it/s]


0.75766 



552it [01:05,  8.38it/s]
477it [00:57,  8.28it/s]


0.86716 



552it [01:05,  8.39it/s]
509it [01:01,  8.28it/s]


0.86063 



477it [00:57,  8.36it/s]
1258it [02:31,  8.32it/s]


0.73743 



477it [00:58,  8.21it/s]
552it [01:06,  8.29it/s]


0.8066 



477it [00:57,  8.35it/s]
509it [01:01,  8.29it/s]


0.85633 



509it [01:00,  8.38it/s]
1258it [02:31,  8.33it/s]


0.74916 



509it [01:00,  8.37it/s]
552it [01:06,  8.28it/s]


0.8096 



509it [01:00,  8.37it/s]
477it [00:57,  8.30it/s]


0.86113 


The face-to-periocular CMC of imdb_wiki :
[0.8274175  0.86728333 0.88373167 0.89362667 0.9009925 ]
It took 38m 19s

The face-to-periocular CMC of ar start



22it [00:03,  6.17it/s]
88it [00:11,  7.54it/s]


0.68071 



22it [00:03,  6.76it/s]
44it [00:06,  7.19it/s]


0.95643 



22it [00:03,  6.85it/s]
110it [00:13,  7.95it/s]


0.90571 



22it [00:03,  6.89it/s]
19it [00:05,  3.55it/s]


0.98167 



88it [00:10,  8.04it/s]
22it [00:03,  6.70it/s]


0.94714 



88it [00:10,  8.08it/s]
44it [00:05,  7.62it/s]


0.99786 



88it [00:10,  8.06it/s]
110it [00:13,  8.03it/s]


0.95514 



88it [00:11,  7.99it/s]
19it [00:05,  3.75it/s]


0.96333 



44it [00:05,  7.60it/s]
22it [00:03,  6.96it/s]


0.96857 



44it [00:05,  7.53it/s]
88it [00:11,  7.97it/s]


0.81857 



44it [00:05,  7.58it/s]
110it [00:13,  8.12it/s]


0.97857 



44it [00:05,  7.65it/s]
19it [00:04,  3.83it/s]


0.99167 



110it [00:13,  8.15it/s]
22it [00:03,  6.87it/s]


0.95571 



110it [00:13,  8.12it/s]
88it [00:10,  8.03it/s]


0.7775 



110it [00:13,  8.20it/s]
44it [00:05,  7.44it/s]


0.99786 



110it [00:13,  8.20it/s]
19it [00:05,  3.71it/s]


0.98667 



19it [00:04,  3.86it/s]
22it [00:03,  7.10it/s]


0.91571 



19it [00:05,  3.78it/s]
88it [00:10,  8.08it/s]


0.66464 



19it [00:05,  3.80it/s]
44it [00:05,  7.66it/s]


0.89857 



19it [00:05,  3.72it/s]
110it [00:13,  8.07it/s]


0.85571 


The face-to-periocular CMC of ar :
[0.909887  0.9291405 0.940528  0.9483945 0.9539845]
It took 10m 19s

The face-to-periocular CMC of ytf start

ytf dataloading takes some time, please wait
ytf dataloading takes some time, please wait
dataloader time elapsed : 26m 19.72s



473it [00:57,  8.23it/s]
119it [00:14,  7.99it/s]


0.72436 

ytf dataloading takes some time, please wait
ytf dataloading takes some time, please wait
dataloader time elapsed : 19m 26.46s



119it [00:14,  8.10it/s]
473it [00:57,  8.26it/s]


0.55196 


The face-to-periocular CMC of ytf :
[0.63816  0.68178  0.703675 0.718305 0.729485]
It took 49m 26s

The face-to-periocular CMC dictionary : 
{'ethnic': array([0.953995, 0.968065, 0.97396 , 0.976825, 0.97868 ]), 'pubfig': array([0.97049167, 0.97919667, 0.9827375 , 0.98477083, 0.98623083]), 'facescrub': array([0.97058167, 0.97709667, 0.979755  , 0.98130833, 0.982425  ]), 'imdb_wiki': array([0.8274175 , 0.86728333, 0.88373167, 0.89362667, 0.9009925 ]), 'ar': array([0.909887 , 0.9291405, 0.940528 , 0.9483945, 0.9539845]), 'ytf': array([0.63816 , 0.68178 , 0.703675, 0.718305, 0.729485])}
It took 2.0h 19.0m


In [9]:
test_f2p_verification_cos_sim(args, model)

The face-to-periocular EER of ethnic start



42it [00:06,  6.90it/s]



The face-to-periocular EER of ethnic : 0.05717

The face-to-periocular EER of pubfig start



25it [00:03,  6.47it/s]



The face-to-periocular EER of pubfig : 0.05094

The face-to-periocular EER of facescrub start



67it [00:08,  7.69it/s]



The face-to-periocular EER of facescrub : 0.02714

The face-to-periocular EER of imdb_wiki start



267it [00:32,  8.32it/s]



The face-to-periocular EER of imdb_wiki : 0.06062

The face-to-periocular EER of ar start



13it [00:04,  2.84it/s]



The face-to-periocular EER of ar : 0.08865

The face-to-periocular EER of ytf start



29it [00:05,  5.37it/s]


The face-to-periocular EER of ytf : 0.14339

The face-to-periocular EER dictionary : 
{'ethnic': 0.05717, 'pubfig': 0.05094, 'facescrub': 0.02714, 'imdb_wiki': 0.06062, 'ar': 0.08865, 'ytf': 0.14339}


In [6]:
test_f2p_identification_kl_div(args, model,T=1)

The face-to-periocular CMC of ethnic with KL Div start



206it [00:12, 16.48it/s]
3022it [02:15, 22.33it/s]


0.93352 



3022it [02:11, 23.06it/s]
206it [00:17, 11.48it/s]


0.97447 


The face-to-periocular CMC of ethnic with KL Div :
[0.953995 0.968065 0.97396  0.976825 0.97868 ]
It took 5m 36s

The face-to-periocular CMC of ar with KL Div start



88it [00:04, 19.52it/s]
350it [00:16, 21.24it/s]


0.68071 



88it [00:04, 19.97it/s]
175it [00:08, 21.19it/s]


0.95643 



88it [00:04, 20.64it/s]
438it [00:19, 22.21it/s]


0.90571 



88it [00:04, 19.58it/s]
75it [00:06, 12.39it/s]


0.98167 



350it [00:15, 22.16it/s]
88it [00:04, 18.88it/s]


0.94714 



350it [00:15, 22.37it/s]
175it [00:08, 20.55it/s]


0.99786 



350it [00:15, 22.32it/s]
438it [00:20, 21.45it/s]


0.95514 



350it [00:15, 22.19it/s]
75it [00:06, 12.34it/s]


0.96333 



175it [00:08, 21.71it/s]
88it [00:04, 20.00it/s]


0.96857 



175it [00:08, 21.26it/s]
350it [00:16, 21.85it/s]


0.81857 



175it [00:08, 21.32it/s]
438it [00:19, 22.04it/s]


0.97857 



175it [00:08, 21.63it/s]
75it [00:06, 12.37it/s]


0.99167 



438it [00:19, 22.51it/s]
88it [00:04, 19.32it/s]


0.95571 



438it [00:19, 22.51it/s]
350it [00:16, 21.00it/s]


0.7775 



438it [00:19, 22.40it/s]
175it [00:08, 20.22it/s]


0.99786 



438it [00:19, 22.52it/s]
75it [00:06, 11.88it/s]


0.98667 



75it [00:06, 12.33it/s]
88it [00:04, 19.96it/s]


0.91571 



75it [00:06, 12.18it/s]
350it [00:15, 21.97it/s]


0.66464 



75it [00:06, 12.22it/s]
175it [00:08, 21.18it/s]


0.89857 



75it [00:06, 12.27it/s]
438it [00:19, 22.19it/s]

0.85571 


The face-to-periocular CMC of ar with KL Div :
[0.909887  0.9291405 0.940528  0.9483945 0.9539845]
It took 12m 25s

The face-to-periocular CMC dictionary with KL Div : 
{'ethnic': array([0.953995, 0.968065, 0.97396 , 0.976825, 0.97868 ]), 'ar': array([0.909887 , 0.9291405, 0.940528 , 0.9483945, 0.9539845])}
It took 0.0h 18.0m


In [6]:
test_f2p_identification_kl_div(args, model,T=2.5)

The face-to-periocular CMC of ethnic with KL Div start



206it [00:14, 14.04it/s]
3022it [02:15, 22.29it/s]


0.93352 



3022it [02:11, 23.02it/s]
206it [00:19, 10.75it/s]


0.97447 


The face-to-periocular CMC of ethnic with KL Div :
[0.953995 0.968065 0.97396  0.976825 0.97868 ]
It took 5m 42s

The face-to-periocular CMC of ar with KL Div start



88it [00:04, 18.57it/s]
350it [00:16, 21.28it/s]


0.68071 



88it [00:04, 20.42it/s]
175it [00:08, 20.93it/s]


0.95643 



88it [00:04, 19.88it/s]
438it [00:19, 22.27it/s]


0.90571 



88it [00:04, 20.42it/s]
75it [00:06, 11.99it/s]


0.98167 



350it [00:15, 22.39it/s]
88it [00:04, 19.17it/s]


0.94714 



350it [00:15, 22.50it/s]
175it [00:08, 20.31it/s]


0.99786 



350it [00:15, 22.28it/s]
438it [00:20, 21.48it/s]


0.95514 



350it [00:15, 22.20it/s]
75it [00:06, 12.48it/s]


0.96333 



175it [00:08, 21.34it/s]
88it [00:04, 20.04it/s]


0.96857 



175it [00:08, 21.36it/s]
350it [00:16, 21.87it/s]


0.81857 



175it [00:08, 21.43it/s]
438it [00:19, 21.98it/s]


0.97857 



175it [00:08, 21.60it/s]
75it [00:05, 12.69it/s]


0.99167 



438it [00:19, 22.51it/s]
88it [00:04, 19.29it/s]


0.95571 



438it [00:19, 22.50it/s]
350it [00:16, 20.86it/s]


0.7775 



438it [00:19, 22.40it/s]
175it [00:08, 20.44it/s]


0.99786 



438it [00:19, 22.46it/s]
75it [00:06, 12.28it/s]


0.98667 



75it [00:05, 12.91it/s]
88it [00:04, 20.05it/s]


0.91571 



75it [00:05, 12.81it/s]
350it [00:15, 22.18it/s]


0.66464 



75it [00:05, 12.74it/s]
175it [00:08, 21.36it/s]


0.89857 



75it [00:05, 12.62it/s]
438it [00:19, 22.08it/s]

0.85571 


The face-to-periocular CMC of ar with KL Div :
[0.909887  0.9291405 0.940528  0.9483945 0.9539845]
It took 12m 26s

The face-to-periocular CMC dictionary with KL Div : 
{'ethnic': array([0.953995, 0.968065, 0.97396 , 0.976825, 0.97868 ]), 'ar': array([0.909887 , 0.9291405, 0.940528 , 0.9483945, 0.9539845])}
It took 0.0h 18.0m


In [6]:
test_f2p_verification_kl_div(args, model,T=1)

The face-to-periocular EER of ethnic with KL divergence start


165it [00:12, 13.50it/s]



face-to-periocular EER of ethnic with KL divergence: 0.05641

The face-to-periocular EER of ar with KL divergence start


50it [00:06,  7.52it/s]



face-to-periocular EER of ar with KL divergence: 0.09321

The face-to-periocular EER dictionary with KL divergence : 
{'ethnic': 0.05641, 'ar': 0.09321}


In [7]:
test_f2p_verification_kl_div(args, model,T=2.5)

The face-to-periocular EER of ethnic with KL divergence start


165it [00:07, 21.31it/s]



face-to-periocular EER of ethnic with KL divergence: 0.06496

The face-to-periocular EER of ar with KL divergence start


50it [00:06,  7.68it/s]



face-to-periocular EER of ar with KL divergence: 0.09759

The face-to-periocular EER dictionary with KL divergence : 
{'ethnic': 0.06496, 'ar': 0.09759}
